/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import DAO.DistribuidorDAO;
import Entidades.Distribuidores;
import Utilidades.IEntitySave;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author camila
 */
public class IngresoFactura extends javax.swing.JFrame implements IEntitySave {

    private boolean primeraVezCambiado = false;
    /**
     * Creates new form IngresoFactura
     */
    public IngresoFactura() {
        initComponents();
        modificarCboNombre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdDistribuidores = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDigitoVerificador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAnios = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboNombreEmpresa = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnAgregarDist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setText("Factura ");

        jLabel2.setText("Id : ");

        txtIdDistribuidores.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdDistribuidoresFocusLost(evt);
            }
        });

        jLabel3.setText("Rut Empresa :");

        jLabel4.setText("-");

        txtDigitoVerificador.setToolTipText("");

        jLabel5.setText("Años de servicio :");
        jLabel5.setToolTipText("");

        jLabel6.setText("Nombre empresa :");

        cboNombreEmpresa.setModel(cboNombreEmpresa.getModel());
        cboNombreEmpresa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNombreEmpresaItemStateChanged(evt);
            }
        });
        cboNombreEmpresa.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                cboNombreEmpresaHierarchyChanged(evt);
            }
        });
        cboNombreEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboNombreEmpresaFocusLost(evt);
            }
        });
        cboNombreEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboNombreEmpresaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboNombreEmpresaMousePressed(evt);
            }
        });
        cboNombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNombreEmpresaActionPerformed(evt);
            }
        });
        cboNombreEmpresa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboNombreEmpresaPropertyChange(evt);
            }
        });
        cboNombreEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboNombreEmpresaKeyPressed(evt);
            }
        });

        jLabel7.setText("Dirección :");

        txtDireccion.setToolTipText("");

        jLabel8.setText("Telefono :");

        jLabel9.setText("Correo :");

        btnAgregarDist.setText("Agregar Distribuidor");
        btnAgregarDist.setToolTipText("");
        btnAgregarDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(770, 770, 770)
                        .addComponent(btnAgregarDist))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(29, 29, 29)
                            .addComponent(txtIdDistribuidores, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(59, 59, 59)
                            .addComponent(jLabel3)
                            .addGap(41, 41, 41)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDigitoVerificador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(cboNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(txtAnios, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(46, 46, 46)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(jLabel9)
                            .addGap(28, 28, 28)
                            .addComponent(txtCorreo))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnAgregarDist))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdDistribuidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDigitoVerificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cboNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(388, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdDistribuidoresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdDistribuidoresFocusLost
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdDistribuidores.getText());
        Distribuidores distribuidor = new DistribuidorDAO().buscarPorId(id);
        if(distribuidor != null){
            txtRut.setText(Integer.toString(distribuidor.getRut()));
            txtDigitoVerificador.setText(Character.toString(distribuidor.getDigitoVerificador()));
            txtAnios.setText(Integer.toString(distribuidor.getAñosDeServicio()));
            txtDireccion.setText(distribuidor.getDireccion());
            txtTelefono.setText(Integer.toString(distribuidor.getTelefono()));
            txtCorreo.setText(distribuidor.getCorreo());
            cboNombreEmpresa.setSelectedItem(distribuidor.getNombreEmpresa());
        }
    }//GEN-LAST:event_txtIdDistribuidoresFocusLost

    private void cboNombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNombreEmpresaActionPerformed
        // TODO add your handling code here:
        if(primeraVezCambiado == false) {
            primeraVezCambiado = true;
            return;
        }
        String nombre = String.valueOf(cboNombreEmpresa.getSelectedItem());
        Distribuidores distribuidor =  new DistribuidorDAO().buscarPorNombre(nombre);
        if(distribuidor != null){
            txtIdDistribuidores.setText(Integer.toString(distribuidor.getId_distribuidores()));
            txtRut.setText(Integer.toString(distribuidor.getRut()));
            txtDigitoVerificador.setText(Character.toString(distribuidor.getDigitoVerificador()));
            txtAnios.setText(Integer.toString(distribuidor.getAñosDeServicio()));
            txtDireccion.setText(distribuidor.getDireccion());
            txtTelefono.setText(Integer.toString(distribuidor.getTelefono()));
            txtCorreo.setText(distribuidor.getCorreo());
        }
        if(cboNombreEmpresa.getSelectedIndex()==0){
            txtIdDistribuidores.setText("");
            txtRut.setText("");
            txtDigitoVerificador.setText("");
            txtAnios.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtCorreo.setText("");
        }
    }//GEN-LAST:event_cboNombreEmpresaActionPerformed

    private void cboNombreEmpresaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboNombreEmpresaPropertyChange

        
    }//GEN-LAST:event_cboNombreEmpresaPropertyChange

    private void cboNombreEmpresaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNombreEmpresaItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboNombreEmpresaItemStateChanged

    private void cboNombreEmpresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboNombreEmpresaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboNombreEmpresaKeyPressed

    private void cboNombreEmpresaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_cboNombreEmpresaHierarchyChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboNombreEmpresaHierarchyChanged

    private void cboNombreEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboNombreEmpresaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboNombreEmpresaMouseClicked

    private void cboNombreEmpresaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboNombreEmpresaMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboNombreEmpresaMousePressed

    private void cboNombreEmpresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboNombreEmpresaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNombreEmpresaFocusLost

    private void btnAgregarDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDistActionPerformed
        // TODO add your handling code here:
        IngresarDistribuidor ingresarD = new IngresarDistribuidor();
        ingresarD.setVisible(true);
        ingresarD.setiEntitySave(this);
    }//GEN-LAST:event_btnAgregarDistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoFactura().setVisible(true);
            }
        });
    }
    
    public void modificarCboNombre(){
        DistribuidorDAO distribuidorDao = new DistribuidorDAO();
        ArrayList<Distribuidores> distribuidores = distribuidorDao.listarDistribuidores();
        cboNombreEmpresa.addItem("Seleccione distribuidor");
        
        for (Distribuidores distribuidor : distribuidores) {
            cboNombreEmpresa.addItem(distribuidor.getNombreEmpresa());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarDist;
    private javax.swing.JComboBox<String> cboNombreEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAnios;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDigitoVerificador;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdDistribuidores;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public void afterSave() {
        cboNombreEmpresa.removeAllItems();
        modificarCboNombre();
    }
}
