/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import DAO.CompraDAO;
import DAO.DetalleCompraDAO;
import DAO.DistribuidorDAO;
import DAO.FacturaDAO;
import DAO.LibrosDAO;
import DAO.MedioPagoDAO;
import DAO.StockDAO;
import Entidades.DetalleCompra;
import Entidades.Distribuidores;
import Entidades.Factura;
import Entidades.ItemCompra;
import Entidades.Libro;
import Entidades.MedioDePago;
import Entidades.StockLibro;
import Utilidades.IEntitySave;
import Utilidades.SuperList;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.accessibility.AccessibleContext;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author camila
 */
public class IngresoFactura extends javax.swing.JFrame implements IEntitySave {

    private boolean primeraVezCambiado = false;
    ArrayList<Libro> libros = new ArrayList<Libro>();
    int contador =1; 
    SuperList<ItemCompra> productosCompra = new SuperList<>();
    int totalSinIVa = 0;
    int totalIva =0;
    int totalConIva = 0;
        
    /**
     * Creates new form IngresoFactura
     */
    public IngresoFactura() {
        initComponents();
        modificarCboNombre();
        listar();
        modificarCboMedioPago();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdDistribuidores = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDigitoVerificador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAnios = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboNombreEmpresa = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnAgregarDist = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtBuscarPorId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBuscarPorISBN = new javax.swing.JTextField();
        btnBuscarPorID = new javax.swing.JButton();
        btnBuscarPorISBN = new javax.swing.JButton();
        btnAgregarLibro = new javax.swing.JButton();
        btnAgregarACompra = new javax.swing.JButton();
        btnEliminarDeCompra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listCompraProductos = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblPrecioNeto = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbltotalConIva = new javax.swing.JLabel();
        cboMedioDePago = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtNumeroFactura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setText("Compra de libros");

        jLabel2.setText("Id : ");

        txtIdDistribuidores.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdDistribuidoresFocusLost(evt);
            }
        });

        jLabel3.setText("Rut Empresa :");

        jLabel4.setText("-");

        txtDigitoVerificador.setToolTipText("");

        jLabel5.setText("Años de servicio :");
        jLabel5.setToolTipText("");

        jLabel6.setText("Nombre empresa :");

        cboNombreEmpresa.setModel(cboNombreEmpresa.getModel());
        cboNombreEmpresa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNombreEmpresaItemStateChanged(evt);
            }
        });
        cboNombreEmpresa.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                cboNombreEmpresaHierarchyChanged(evt);
            }
        });
        cboNombreEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboNombreEmpresaFocusLost(evt);
            }
        });
        cboNombreEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboNombreEmpresaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboNombreEmpresaMousePressed(evt);
            }
        });
        cboNombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNombreEmpresaActionPerformed(evt);
            }
        });
        cboNombreEmpresa.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cboNombreEmpresaPropertyChange(evt);
            }
        });
        cboNombreEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboNombreEmpresaKeyPressed(evt);
            }
        });

        jLabel7.setText("Dirección :");

        txtDireccion.setToolTipText("");

        jLabel8.setText("Telefono :");

        jLabel9.setText("Correo :");

        btnAgregarDist.setText("Agregar Distribuidor");
        btnAgregarDist.setToolTipText("");
        btnAgregarDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDistActionPerformed(evt);
            }
        });

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Numero de serie", "Titulo", "Año de publicacion", "Editorial", "Stock actual"
            }
        ));
        jScrollPane1.setViewportView(tblLibros);
        if (tblLibros.getColumnModel().getColumnCount() > 0) {
            tblLibros.getColumnModel().getColumn(0).setHeaderValue("Id ");
            tblLibros.getColumnModel().getColumn(1).setHeaderValue("Numero serie");
            tblLibros.getColumnModel().getColumn(2).setHeaderValue("Titulo");
            tblLibros.getColumnModel().getColumn(3).setHeaderValue("Año");
        }

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLabel10.setText("Buscar por Id : ");

        txtBuscarPorId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarPorIdActionPerformed(evt);
            }
        });

        jLabel11.setText("Buscar por numero de serie :");

        btnBuscarPorID.setText("Buscar");
        btnBuscarPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorIDActionPerformed(evt);
            }
        });

        btnBuscarPorISBN.setText("Buscar");
        btnBuscarPorISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorISBNActionPerformed(evt);
            }
        });

        btnAgregarLibro.setText("Agregar Libro");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });

        btnAgregarACompra.setText("Agregar a compra");
        btnAgregarACompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarACompraMouseClicked(evt);
            }
        });
        btnAgregarACompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarACompraActionPerformed(evt);
            }
        });

        btnEliminarDeCompra.setText("Eliminar de compra");
        btnEliminarDeCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDeCompraActionPerformed(evt);
            }
        });

        listCompraProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCompraProductos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listCompraProductosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listCompraProductos);

        jLabel12.setText("Id libro | cantidad | Precio  |Total");

        jLabel13.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel13.setText("Precio neto :");

        lblPrecioNeto.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel14.setText("IVA :");

        lblIVA.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel15.setText("Total : ");

        lbltotalConIva.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N

        cboMedioDePago.setModel(cboMedioDePago.getModel());

        jLabel16.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel16.setText("Medio de Pago :");

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel17.setText("Numero de factura : ");

        txtNumeroFactura.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(237, 237, 237)
                                .addComponent(jLabel17)
                                .addGap(31, 31, 31)
                                .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarDist))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAnios, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtIdDistribuidores, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(41, 41, 41)
                                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDigitoVerificador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(101, 101, 101))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminarDeCompra)
                                    .addComponent(btnAgregarACompra))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnCancelar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnComprar))
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblPrecioNeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblIVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(18, 18, 18)
                                            .addComponent(lbltotalConIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(cboMedioDePago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBuscarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5))
                                .addGap(34, 34, 34)
                                .addComponent(btnBuscarPorID)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscarPorISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarPorISBN)
                                .addGap(18, 18, 18)
                                .addComponent(btnListar)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(btnAgregarLibro)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnAgregarDist)
                    .addComponent(jLabel17)
                    .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdDistribuidores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtDigitoVerificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cboNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListar)
                    .addComponent(txtBuscarPorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtBuscarPorISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPorID)
                    .addComponent(btnBuscarPorISBN)
                    .addComponent(btnAgregarLibro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnAgregarACompra)
                                .addGap(35, 35, 35)
                                .addComponent(btnEliminarDeCompra))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblPrecioNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lbltotalConIva, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboMedioDePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnComprar)
                            .addComponent(btnCancelar))))
                .addGap(584, 584, 584))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdDistribuidoresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdDistribuidoresFocusLost
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdDistribuidores.getText());
        Distribuidores distribuidor = new DistribuidorDAO().buscarPorId(id);
        if(distribuidor != null){
            txtRut.setText(Integer.toString(distribuidor.getRut()));
            txtDigitoVerificador.setText(Character.toString(distribuidor.getDigitoVerificador()));
            txtAnios.setText(Integer.toString(distribuidor.getAñosDeServicio()));
            txtDireccion.setText(distribuidor.getDireccion());
            txtTelefono.setText(Integer.toString(distribuidor.getTelefono()));
            txtCorreo.setText(distribuidor.getCorreo());
            cboNombreEmpresa.setSelectedItem(distribuidor.getNombreEmpresa());
        }
    }//GEN-LAST:event_txtIdDistribuidoresFocusLost

    private void cboNombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNombreEmpresaActionPerformed
        // TODO add your handling code here:
        if(primeraVezCambiado == false) {
            primeraVezCambiado = true;
            return;
        }
        String nombre = String.valueOf(cboNombreEmpresa.getSelectedItem());
        Distribuidores distribuidor =  new DistribuidorDAO().buscarPorNombre(nombre);
        if(distribuidor != null){
            txtIdDistribuidores.setText(Integer.toString(distribuidor.getId_distribuidores()));
            txtRut.setText(Integer.toString(distribuidor.getRut()));
            txtDigitoVerificador.setText(Character.toString(distribuidor.getDigitoVerificador()));
            txtAnios.setText(Integer.toString(distribuidor.getAñosDeServicio()));
            txtDireccion.setText(distribuidor.getDireccion());
            txtTelefono.setText(Integer.toString(distribuidor.getTelefono()));
            txtCorreo.setText(distribuidor.getCorreo());
        }
        if(cboNombreEmpresa.getSelectedIndex()==0){
            txtIdDistribuidores.setText("");
            txtRut.setText("");
            txtDigitoVerificador.setText("");
            txtAnios.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtCorreo.setText("");
        }
    }//GEN-LAST:event_cboNombreEmpresaActionPerformed

    private void cboNombreEmpresaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cboNombreEmpresaPropertyChange

        
    }//GEN-LAST:event_cboNombreEmpresaPropertyChange

    private void cboNombreEmpresaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNombreEmpresaItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboNombreEmpresaItemStateChanged

    private void cboNombreEmpresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboNombreEmpresaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboNombreEmpresaKeyPressed

    private void cboNombreEmpresaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_cboNombreEmpresaHierarchyChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboNombreEmpresaHierarchyChanged

    private void cboNombreEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboNombreEmpresaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboNombreEmpresaMouseClicked

    private void cboNombreEmpresaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboNombreEmpresaMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboNombreEmpresaMousePressed

    private void cboNombreEmpresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboNombreEmpresaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNombreEmpresaFocusLost

    private void btnAgregarDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDistActionPerformed
        // TODO add your handling code here:
        IngresarDistribuidor ingresarD = new IngresarDistribuidor();
        ingresarD.setVisible(true);
        ingresarD.setiEntitySave(this);
    }//GEN-LAST:event_btnAgregarDistActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_btnListarActionPerformed

    private void txtBuscarPorIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarPorIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPorIdActionPerformed

    private void btnBuscarPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorIDActionPerformed
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_btnBuscarPorIDActionPerformed

    private void btnBuscarPorISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorISBNActionPerformed
        // TODO add your handling code here:
        listar();
    }//GEN-LAST:event_btnBuscarPorISBNActionPerformed

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        // TODO add your handling code here:
        IngresarLibro ingresarLibro =  new IngresarLibro();
        ingresarLibro.setVisible(true);
        
    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    private void btnAgregarACompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarACompraActionPerformed
        // TODO add your handling code here:
        int cantidadIngresada = 0;
        int precioUnitarioIngresado = 0;
        int subtotalProducto =0;
        //contador ++;
        //String[] productos = new String[contador];
        int seleccionado = tblLibros.getSelectedRow();
        if(seleccionado == -1){
            JOptionPane.showMessageDialog(null, "Selecccione al menos un libro");
        }else{
            for (Libro libro : libros) {
                int id = this.libros.get(seleccionado).getId_libro();
                                        
                JTextField txtCantidad = new JTextField();
                JTextField txtPrecioUnitario = new JTextField();
                Object[] mensaje= {
                    "Ingrese Cantidad :", txtCantidad,
                    "Ingrese Precio Unitario:", txtPrecioUnitario,
                };
                int option = JOptionPane.showConfirmDialog(null , mensaje,"¿Cuantos desea comprar ?",0);
                if(option == JOptionPane.OK_OPTION){
                    cantidadIngresada= Integer.parseInt(txtCantidad.getText());
                    precioUnitarioIngresado = Integer.parseInt(txtPrecioUnitario.getText());
                    
                                        
                }
                subtotalProducto= cantidadIngresada * precioUnitarioIngresado;
                ItemCompra item = new ItemCompra();
                item.setId_libro(id);
                item.setCantidad(cantidadIngresada);
                item.setPrecioUnitario(precioUnitarioIngresado);
                item.setTotal(subtotalProducto);
                
                productosCompra.add(item);
                
                listCompraProductos.setListData(productosCompra.getArray());
                totales();
                return;
            }
            
        }
        
        
    }//GEN-LAST:event_btnAgregarACompraActionPerformed

    private void btnAgregarACompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarACompraMouseClicked
        // TODO add your handling code here:
        contador ++;
    }//GEN-LAST:event_btnAgregarACompraMouseClicked

    private void btnEliminarDeCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDeCompraActionPerformed
        // TODO add your handling code here:
        int indice =  listCompraProductos.getSelectedIndex();
        productosCompra.remove(indice);
        listCompraProductos.setListData(productosCompra.getArray());
        totales();
    }//GEN-LAST:event_btnEliminarDeCompraActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void listCompraProductosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCompraProductosValueChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_listCompraProductosValueChanged

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        if(cboMedioDePago.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un medio de pago");
        }else{
        
            Factura factura = new Factura();
            factura.setPrecioNeto(totalSinIVa);
            factura.setPrecioConIVA(totalIva);
            factura.setCostoConIVA(totalConIva);
            LocalDateTime dateTime = LocalDateTime.now();
            DateTimeFormatter form = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            String Hoy = String.valueOf(dateTime.format(form));
            String fecha = Hoy.substring(0, 10);
            String hora = Hoy.substring(11, 19);
            factura.setHoraDeCompra(hora);
            factura.setFechaDeCompra(fecha);
            MedioDePago medioP = new MedioDePago();
            int id = cboMedioDePago.getSelectedIndex();
            String medio = String.valueOf(cboMedioDePago.getSelectedItem());
            medioP.setId_medio_de_pago(id);
            medioP.setMedioDePago(medio);
            factura.setMedio_de_pago(medioP);
            factura.setNumeroFactura(Integer.parseInt(txtNumeroFactura.getText()));
            boolean fueAgregadoF =false;
            if(txtNumeroFactura.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Debe ingresar el numero de factura");
            }else{
                fueAgregadoF=new FacturaDAO().fueAgregado(factura);
            }
             

            if(txtIdDistribuidores.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Debe seleccionar un distribuidor");
            }else{
                
                int idDist = Integer.parseInt(txtIdDistribuidores.getText());
                int idFact =  new FacturaDAO().buscarUltimo().getId_factura();
                
                boolean fueAgregadaTCom = new CompraDAO().agregarCompra(idDist, idFact);
                DetalleCompra detalleC = new DetalleCompra();
                int idCom = new CompraDAO().buscarUltimo().getId_compra();
                detalleC.setIdCompra(idCom);
                boolean fueAgregadaRCL = false;
                boolean fueAgregadoStock =false;
                for (ItemCompra itemCompra : productosCompra) {
                    int idLib = itemCompra.getId_libro();
                    detalleC.setIdLibro(idLib);
                    fueAgregadaRCL = new DetalleCompraDAO().agregarDetalleCompra(detalleC);
                    StockLibro stock = new StockLibro();
                    stock.setId_libro(idLib);
                    int stockActual = new StockDAO().bucarPorIdLibro(idLib).getStock_libro();
                    int stockNuevo = stockActual + itemCompra.getCantidad();
                    stock.setStock_libro(stockNuevo);
                    fueAgregadoStock = new StockDAO().modificarStock(stock);
                    
                }
                if(fueAgregadoF== true && fueAgregadaTCom == true && fueAgregadaRCL== true && fueAgregadoStock == true){
                    
                    JOptionPane.showMessageDialog(null, "Fue agregada exitosamente su compra ");
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "No se ha podido realizar su compra");
                }
                
            }
            
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoFactura().setVisible(true);
            }
        });
    }
    
    public void modificarCboNombre(){
        DistribuidorDAO distribuidorDao = new DistribuidorDAO();
        ArrayList<Distribuidores> distribuidores = distribuidorDao.listarDistribuidores();
        cboNombreEmpresa.addItem("Seleccione distribuidor");
        
        for (Distribuidores distribuidor : distribuidores) {
            cboNombreEmpresa.addItem(distribuidor.getNombreEmpresa());
        }
    }
    
    public void listar(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Numero de serie");
        modelo.addColumn("Titulo");
        modelo.addColumn("Año publicación");
        modelo.addColumn("Editorial");
        modelo.addColumn("Stock Actual");
        if(txtBuscarPorId.getText().equals("") && txtBuscarPorISBN.getText().equals("")){
            libros = new LibrosDAO().listarTodo();
        }else if(txtBuscarPorISBN.getText().equals("")){
            libros.clear();
            Libro libro = new LibrosDAO().buscarPorId(Integer.parseInt(txtBuscarPorId.getText()));
            if(libro == null){
                JOptionPane.showMessageDialog(null, "El libro buscado no existe");
                return;
            }
            libros.add(libro);
        }else if(txtBuscarPorId.getText().equals("")){
            libros.clear();
            Libro libro = new LibrosDAO().buscarPorNSerie(Integer.parseInt(txtBuscarPorISBN.getText()));
            if(libro == null){
                JOptionPane.showMessageDialog(null, "El libro buscado no existe");
                return;
            }
            libros.add(libro);
            
        }
        
        
        for (Libro libro : libros) {
            String[] fila = new String[6];
            fila[0] = Integer.toString(libro.getId_libro());
            fila[1] = Integer.toString(libro.getNumeroSerie());
            fila[2] = libro.getTitulo();
            fila[3] = Integer.toString(libro.getAnio_publicacion());
            fila[4] = libro.getEditorial().getEditorial();
            fila[5] = Integer.toString(libro.getStock().getStock_libro());
            
            modelo.addRow(fila);
        }
        tblLibros.setModel(modelo);
        
    }
    
    public void totales(){
        totalSinIVa=0;
        for (ItemCompra itemCompra : productosCompra) {
            totalSinIVa += itemCompra.getTotal();
        }
        
        totalIva = (int) (totalSinIVa*0.19);
       
        totalConIva = (int)(totalSinIVa + totalIva);
        
        lblPrecioNeto.setText(Integer.toString(totalSinIVa));
        lblIVA.setText(Integer.toString(totalIva));
        lbltotalConIva.setText(Integer.toString(totalConIva));
        
    }
    
    public void modificarCboMedioPago(){
        MedioPagoDAO medioDao = new MedioPagoDAO();
        ArrayList<MedioDePago> medio = medioDao.listarMediosDePago();
        cboMedioDePago.addItem("Seleccione");
        for (MedioDePago medioDePago : medio) {
            cboMedioDePago.addItem(medioDePago.getMedioDePago());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarACompra;
    private javax.swing.JButton btnAgregarDist;
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnBuscarPorID;
    private javax.swing.JButton btnBuscarPorISBN;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEliminarDeCompra;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> cboMedioDePago;
    private javax.swing.JComboBox<String> cboNombreEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblPrecioNeto;
    private javax.swing.JLabel lbltotalConIva;
    private javax.swing.JList<String> listCompraProductos;
    private javax.swing.JTable tblLibros;
    private javax.swing.JTextField txtAnios;
    private javax.swing.JTextField txtBuscarPorISBN;
    private javax.swing.JTextField txtBuscarPorId;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDigitoVerificador;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdDistribuidores;
    private javax.swing.JTextField txtNumeroFactura;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public void afterSave() {
        cboNombreEmpresa.removeAllItems();
        modificarCboNombre();
        
    }

    private int indexOf(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
